### ISSUE TITLE
`Expected to find json` error, but valid `reader.Value` content.

### ISSUE THREAD

**Issue by pkesseli** [codecutout/JsonApiSerializer#135]
We try to deserialise an object from an Azure Function's `HttpRequest.Body` as follows:

```csharp
string serialisedProject;
using (var reader = new System.IO.StreamReader(req.Body)) { serialisedProject = await reader.ReadToEndAsync(); }
Entity.Wpml.Project project = Newtonsoft.Json.JsonConvert.DeserializeObject<Entity.Wpml.Project>(serialisedProject, Settings.DEFAULT); }
```

where `Settings.DEFAULT` is:

```csharp
static class Settings
{
  internal static readonly JsonApiSerializerSettings DEFAULT = new JsonApiSerializerSettings()
  {
    Converters = { new StringEnumConverter(typeof(SnakeCaseNamingStrategy)) }
  };

  static Settings()
  {
    var contractResolver = DEFAULT.ContractResolver as DefaultContractResolver;
    contractResolver.NamingStrategy = new SnakeCaseNamingStrategy();
  }
}
```

This yields the following error:

```
Expected to find json object at path '' but found '{"data": {"id": "1","type": "project","attributes": {"name": "Example project name","deadline": 1633013806}}}'
at JsonApiSerializer.Util.ReaderUtil.<IterateProperties>d__1.MoveNext()
at JsonApiSerializer.JsonConverters.DocumentRootConverter.ReadJson(JsonReader reader,Type objectType,Object existingValue,JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter,JsonReader reader,Type objectType,Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader,Type objectType,Boolean checkAdditionalContent)
at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader,Type objectType)
at JsonApiSerializer.JsonConverters.DocumentRootConverter.ResolveAsRootData(JsonReader reader,Type objectType,JsonSerializer serializer)
at JsonApiSerializer.JsonConverters.ResourceObjectConverter.ReadJson(JsonReader reader,Type objectType,Object existingValue,JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter,JsonReader reader,Type objectType,Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader,Type objectType,Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader,Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value,Type type,JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value,JsonSerializerSettings settings)
at async Beo.Diction.Wpml.Function.Projects.Create(HttpRequest req,TableClient projects,TableClient users,ILogger logger) at D:\Users\pkesseli\Software\Function\Projects.cs : 40
```

I cannot reproduce this locally with the same string, only in the Azure Function. The JSON in the "but found" portion looks perfectly valid to me. Any indication what could cause this error when `reader.Value` looks like valid JSON content?

**Comment by pkesseli** [comment]
It appears to have been an issue on the client side. `RestSharp` sent the data as a JSON string with that exact content, rather than a JSON object.
