### ISSUE TITLE
Deserialization error: Expected to find json object at path ''

### ISSUE THREAD

**Issue by toverux** [codecutout/JsonApiSerializer#31]
Hello,

I get an error when trying to deserialize lists of resources:

```
JsonApiSerializer.Exceptions.JsonApiFormatException: Expected to find json object at path ''
  at JsonApiSerializer.Util.ReaderUtil+<IterateProperties>d__1.MoveNext () [0x000ad] in <114082c9b9634d14a07a89c38a135e48>:0 
```

<details>
<summary>Full relevant stack trace</summary>

```
JsonApiSerializer.Exceptions.JsonApiFormatException: Expected to find json object at path ''
  at JsonApiSerializer.Util.ReaderUtil+<IterateProperties>d__1.MoveNext () [0x000ad] in <114082c9b9634d14a07a89c38a135e48>:0 
  at JsonApiSerializer.Util.ReaderUtil.ReadAheadToIdentifyObject (JsonApiSerializer.Util.ForkableJsonReader reader) [0x000cf] in <114082c9b9634d14a07a89c38a135e48>:0 
  at JsonApiSerializer.JsonConverters.ResourceObjectConverter+<>c__DisplayClass3_0.<ReadJson>b__0 (JsonApiSerializer.Util.ForkableJsonReader dataReader) [0x00033] in <114082c9b9634d14a07a89c38a135e48>:0 
  at JsonApiSerializer.Util.ReaderUtil.ReadInto[TReader,TResult] (TReader reader, System.Text.RegularExpressions.Regex pathRegex, System.Func`2[T,TResult] action) [0x0000d] in <114082c9b9634d14a07a89c38a135e48>:0 
  at JsonApiSerializer.JsonConverters.ResourceObjectConverter.ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) [0x0004b] in <114082c9b9634d14a07a89c38a135e48>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) [0x00055] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00008] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at JsonApiSerializer.Util.ReaderUtil.TryPopulateProperty (Newtonsoft.Json.JsonSerializer serializer, System.Object obj, Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonReader value) [0x00012] in <114082c9b9634d14a07a89c38a135e48>:0 
  at JsonApiSerializer.JsonConverters.ResourceObjectConverter.PopulateProperties (Newtonsoft.Json.JsonSerializer serializer, System.Object obj, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract) [0x00027] in <114082c9b9634d14a07a89c38a135e48>:0 
  at JsonApiSerializer.JsonConverters.ResourceObjectConverter+<>c__DisplayClass3_0.<ReadJson>b__0 (JsonApiSerializer.Util.ForkableJsonReader dataReader) [0x000fb] in <114082c9b9634d14a07a89c38a135e48>:0 
  at JsonApiSerializer.Util.ReaderUtil.ReadInto[TReader,TResult] (TReader reader, System.Text.RegularExpressions.Regex pathRegex, System.Func`2[T,TResult] action) [0x0000d] in <114082c9b9634d14a07a89c38a135e48>:0 
  at JsonApiSerializer.JsonConverters.ResourceObjectConverter.ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) [0x0004b] in <114082c9b9634d14a07a89c38a135e48>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) [0x00055] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00008] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at JsonApiSerializer.JsonConverters.ResourceObjectListConverter+<>c__DisplayClass4_0.<ReadJson>b__0 (System.Object x) [0x00000] in <114082c9b9634d14a07a89c38a135e48>:0 
  at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].ToArray () [0x0001d] in <b5bd9d990a0b4733885e90ca5ec6c0fb>:0 
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <b5bd9d990a0b4733885e90ca5ec6c0fb>:0 
  at JsonApiSerializer.Util.ListUtil.CreateList (System.Type listType, System.Collections.Generic.IEnumerable`1[T] elements) [0x00032] in <114082c9b9634d14a07a89c38a135e48>:0 
  at JsonApiSerializer.JsonConverters.ResourceObjectListConverter.ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) [0x00088] in <114082c9b9634d14a07a89c38a135e48>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) [0x00055] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00008] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at JsonApiSerializer.JsonConverters.DocumentRootConverter.ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) [0x000d9] in <114082c9b9634d14a07a89c38a135e48>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) [0x00055] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00008] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at JsonApiSerializer.JsonConverters.DocumentRootConverter.TryResolveAsRootData (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.JsonSerializer serializer, System.Object& obj) [0x00060] in <114082c9b9634d14a07a89c38a135e48>:0 
  at JsonApiSerializer.JsonConverters.ResourceObjectListConverter.ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) [0x00015] in <114082c9b9634d14a07a89c38a135e48>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) [0x00055] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <c19705166c7c4a608e182e859c4de6d2>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <c19705166c7c4a608e182e859c4de6d2>:0
```
</details>

---------------------------

The minimal amount of JSON to reproduce seems to be:

```json
{
   "data": [
      {
         "type": "media",
         "id": "42170",
         "attributes": {
         }
      }
   ],
   "included": [
   ]
}
```

The type I try to deserialize from that is `Media[]` or `List<Media>` (tried both).

`JsonSerializationException.SpecificationInformation` is `null`.

The JSON posted above seems valid though (and I get no error if the array is empty). Moreover, I'm pretty sure this worked before on another endpoint, unfortunately it's broken today and I don't have an hand on the API I get JSON from, so I can't diff the payloads.

Thanks for your help (and thanks for the package, that saved me a lot of time, but I'm a bit stuck here :smile:).

**Comment by alex-davies** [comment]
I cant seem to reproduce your error, the following test case passes for me

```csharp
    public class Media
    {
        public string Id { get; set; }
        public string Type { get; set; }
    }

    public class DeserializationIssue31Test
    {
        [Fact]
        public void When_deserialise_simple_object_should_deserialize()
        {
            var json = @"
{
    ""data"": [{
        ""type"": ""media"",
        ""id"": ""42170"",
        ""attributes"": {
        }
    }],
   ""included"": [
   ]
}";
            var data = JsonConvert.DeserializeObject<Media[]>(json, new JsonApiSerializerSettings());

            Assert.Single(data);
            Assert.Equal("42170", data[0].Id);
        }
```

are you using specific settings in the `JsonApiSerializerSettings`?

**Comment by toverux** [comment]
Thanks for your answer. Here's what I have:

```cs
var resourceConverter = new TypeBasedResourceObjectConverter(typeof(IResource));

var jsonSettings = new JsonApiSerializerSettings(resourceConverter) {
    NullValueHandling = NullValueHandling.Ignore
};
```

<details>
<summary>Just in case, this is <code>TypeBasedResourceObjectConverter</code></summary>

```cs
public class TypeBasedResourceObjectConverter : JsonApiSerializer.JsonConverters.ResourceObjectConverter
{
    private readonly Type baseResourceType;

    public TypeBasedResourceObjectConverter(Type baseResourceType)
    {
        this.baseResourceType = baseResourceType;
    }

    public override bool CanConvert(Type objectType)
    {
        return baseResourceType.IsAssignableFrom(objectType) || base.CanConvert(objectType);
    }
}
```
</details>

<details>
<summary>And <code>Media</code></summary>

```cs
public class Media : IResource
{
    public string Id { get; set; }

    public DateTime Published { get; set; }

    public uint Duration { get; set; }

    public List<Specialty> Specialties { get; set; }

    public Type Type { get; set; }
}
```
</details>

**Comment by alex-davies** [comment]
Even using your converter (which seems fine) im still struggling to reproduce the error you are seeing.

I am however getting an error where it cant deserialize the string `"media"` into an object of type `Type`. The `Type` property should be a of type `string`

Although relooking at your error you are getting it indicates the string you are passing it doesn't have a json object at the root. Are you reading your json string from a file? could there be invisible unicode characters at the beginning?

Would you be able to provide an single self contained test case that is failing on your end?

**Comment by toverux** [comment]
@codecutout Hi, thanks again for your help!

> I am however getting an error where it cant deserialize the string "media" into an object of type Type. The Type property should be a of type string

It's not `System.Type` but a resource class in the same namespace, I should have mentioned that :smile:
It often bites me, but not this time, it resolves to the correct type...

However, yes, the problem seems to come from that. But it's not because the Type property is of type Type, but _because it's named "Type"_.

If I do this:

```diff
-public Type Type { get; set; }
+public Type Typo { get; set; }
```

It works. I mean, it deserializes the object correctly, but of course I can't retrieve the real `type` value now. So I tried:

```diff
+[JsonProperty("type")]
-public Type Type { get; set; }
+public Type SafelyNamedType { get; set; }
```

But it still crashes. So the crash comes from the fact that the JSON property (not the C# one, not the type, etc), is originally named "`type`". If I rename it to "`typo`" again on the client, no errors.

**Comment by toverux** [comment]
Oh my, I've just seen that: https://github.com/codecutout/JsonApiSerializer#types

My property name is conflicting with this feature (that's why I didn't understood _"The Type property should be a of type string"_). -- But I still don't know why it fails with `[JsonProperty("type")]` then.

But clearly there was a misunderstanding here :smile:

What could be done for this? An attribute like `[JsonApiType(name: "some_type")]` would be better than a `string Type { get; }` property (*) but that's a breaking change. However, I will have a hard time to explain the team that works on the API that the field should be renamed...

(*): would also allow JsonApiSerializer to recognize resource types because they are tagged, and not because they have an "Id" property.

**Comment by alex-davies** [comment]
jsonapi specification actually says you cant have an attribute or relationship called `type` (http://jsonapi.org/format/#document-resource-object-fields), so that should be an easier sell to your teammates to rename it.

On deserialization you don't need to define type at all on your model. We do not setup any link between the json:api `type` and the `System.Type`. However if you do want to know what the type value was then add a Type property on the model we will populate it.

Serialization is a slightly different story, we do need a type to be json:api compliant and if you do not specify it we just use the class name, however if someone wants to overwrite it then they specify the type as a field. This gives good symmetry to the serialization and deserialization; the `type` property on your object maps directly to the json:api `type` property

However on saying that i'm not opposed to having the default behaviour also check for an attribute. We have had cases where a service wanted to use content negotiation to determine if it should use regular json or json:api. Having a Type on the model meant having an undesired `type` field on the regular json object

The reason the default behaviour is driven using the "Id" property is simply because json:api requires all resources to have an id (the notable exception being create requests) and an Id not something we want to be autogenerating for you. It is also very wierd to give an Id to something that is not a standalone resource. In your example I would have just added an Id property to your `IResource` interface

**Comment by toverux** [comment]
> jsonapi specification actually says you cant have an attribute or relationship called type (http://jsonapi.org/format/#document-resource-object-fields), so that should be an easier sell to your teammates to rename it.

Indeed! I really didn't knew about that. I find it to be a rude limitation though, as the type is specified in the resource object. This should be let as an implementation detail/recommendation in my opinion - like it's done in this library.

> This gives good symmetry to the serialization and deserialization

That's a good point yes, didn't thought about that since I haven't used `Type` yet.

Although those two limitations are coming into my way and are a bit opinionated/magic to me (which can cause frictions with real world use cases and implementations, like here), I can totally understand your arguments on this. It should also not cause so much problems with the rest of the team too I think, since I know they have a presentation layer, so the property in the API can be renamed without impacting the persistence/business layer.

Will discuss that with them, I think we can close this in the meantime, except if you're still interested to make the library more flexible :) Thanks for your time and sorry for the issue -- really thought it was a solid bug :(

**Comment by WtheFourth** [comment]
This cropped up for me today as well, trying to deserialize the following: 

POST body of type `application/vnd.api+json`:
```
{
    "data": [
        {
            "id": "1",
            "type": "feature-toggle",
            "attributes": {
                "toggle-name": "FeatureToggle.TestFeatureToggle",
                "toggle-value": "True"
            }
        }
    ]
}
```

... into this C# object: 
 ```
public class FeatureToggle
{
    [JsonProperty("type")]
    public string Type { get; set; } = "feature-toggle";
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("toggle-name")]
    public string ToggleName { get; set; }
    [JsonProperty("toggle-value")]
    public string ToggleValue { get; set; }
}
```

The error occurs in this function in my media formatter: 

```
public override object ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
{
    using (var sr = new StreamReader(readStream))
    {
        var fullRead = sr.ReadToEnd();
        var converted = JsonConvert.DeserializeObject(fullRead, type, new JsonApiSerializerSettings()); // error happens here
        return converted;
    }
}
```

I realize this is a closed issue, but I didn't want to open another with exactly the same name. Does anything look wrong here?

**Comment by alex-davies** [comment]
Everything looks fine in your example a simple test case works fine
```csharp
public class Issue31
    {
        public class FeatureToggle
        {
            [JsonProperty("type")]
            public string Type { get; set; } = "feature-toggle";
            [JsonProperty("id")]
            public string Id { get; set; }
            [JsonProperty("toggle-name")]
            public string ToggleName { get; set; }
            [JsonProperty("toggle-value")]
            public string ToggleValue { get; set; }
        }

        [Fact]
        public void Feature_toggle_works()
        {
            var json = @"not valid{
    ""data"": [
            {
                ""id"": ""1"",
                ""type"": ""feature-toggle"",
                ""attributes"": {
                    ""toggle-name"": ""FeatureToggle.TestFeatureToggle"",
                    ""toggle-value"": ""True""
                }
            }
            ]
        }";

            var result = JsonConvert.DeserializeObject<FeatureToggle[]>(
                json,
                new JsonApiSerializerSettings());

            Assert.NotNull(result);

        }
```

I would check what the value of fullRead is, as i'm not sure if you should be reading from `readStream` or from `content`. your fullRead may have more than just the request body. This error usually means you are not passing in a valid json object.

**Comment by WtheFourth** [comment]
Hm, I wonder if it's because of the escaping that the WebAPI is doing back there?

Here's my `string` value of both `readStream` and `content`:

```
"{\"data\": [{\"type\": \"feature-toggle\", \"id\": \"1\", \"attributes\": {\"toggle-name\": \"FeatureToggle.TestFeatureToggle\",\"toggle-value\": \"True\"}}]}"
```

**Comment by alex-davies** [comment]
I think I know what it is.

the value of `type` is probably `FeatureToggle` and the json is for a list of items, the `type` should probably be something like `FeatureToggle[]`

I agree this error message is not very helpful and we should probably look out for such cases and give a more meaningful error. I will keep this issue open and look into a better error message.

Regardless of the error message content you will need to change your `type` to be a list of items

**Comment by WtheFourth** [comment]
I tried it as both `FeatureToggle[]` and as `List<FeatureToggle>` with the same result. Any other ideas?

**Comment by WtheFourth** [comment]
Hm, I had already said I got the same result from both `FeatureToggle[]` and `List<FeatureToggle>`, but that wasn't true. I got this `System.NullReferenceException`: 

```
at JsonApiSerializer.JsonConverters.ResourceObjectConverter.<>c__DisplayClass3_0.<ReadJson>b__0(ForkableJsonReader dataReader)
at JsonApiSerializer.Util.ReaderUtil.ReadInto[TReader,TResult](TReader reader, Regex pathRegex, Func`2 action)
at JsonApiSerializer.JsonConverters.ResourceObjectConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
at JsonApiSerializer.JsonConverters.ResourceObjectListConverter.<>c__DisplayClass4_0.<ReadJson>b__0(Object x)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at JsonApiSerializer.Util.ListUtil.CreateList(Type listType, IEnumerable`1 elements)
at JsonApiSerializer.JsonConverters.ResourceObjectListConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
at JsonApiSerializer.JsonConverters.DocumentRootConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
at JsonApiSerializer.JsonConverters.DocumentRootConverter.TryResolveAsRootData(JsonReader reader, Type objectType, JsonSerializer serializer, Object& obj)
at JsonApiSerializer.JsonConverters.ResourceObjectListConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at FeatureToggleAPI.Formatters.JsonApiFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger) in C:\\git\\web-feature-toggle\\api\\FeatureToggleAPI\\Formatters\\JsonApiFormatter.cs:line 63
at System.Net.Http.Formatting.BufferedMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
at System.Net.Http.Formatting.BufferedMediaTypeFormatter.ReadFromStreamSync(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
at System.Net.Http.Formatting.BufferedMediaTypeFormatter.ReadFromStreamAsync(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
```

**Comment by alex-davies** [comment]
That sounds more serious. 

I cant reproduce, can you create an isolated test case similar to my `Issue31` test case I posted above?

**Comment by WtheFourth** [comment]
I will this afternoon or this coming weekend.

**Comment by WtheFourth** [comment]
So, I wrote a similar test to yours, and the test seems to work with the JSON exactly as it is in my example above. I'm not sure why it's not working in my actual application, but I'll continue to dig. If I find anything, I'll make a note of it here.

**Comment by btecu** [comment]
@WtheFourth I also ran into this issue today. In my case the error was because my model had a required field (`Created`) but I was hoping to set it on the api and not on the client. It didn't serialize until I fixed it - set `Created` on the client or mark it as nullable.
