### ISSUE TITLE
{"Expected to find json object at"}

### ISSUE THREAD

**Issue by ThalusUlysses** [codecutout/JsonApiSerializer#8]
Serialized an object with:

            var t = JsonConvert.SerializeObject(allMethod.Data, new JsonApiSerializerSettings());
            var tt = JsonConvert.DeserializeObject<Compound[]>(t, new JsonApiSerializerSettings());

where allMethod.Data is Compound[]. During deserialize I get the following Exception

JsonApiSerializer.Exceptions.JsonApiFormatException was unhandled
  HResult=-2146233088
  Message=Expected to find json object at
  Path=""
  Source=JsonApiSerializer
  StackTrace:
       at JsonApiSerializer.Util.ReaderUtil.<IterateProperties>d__1.MoveNext()
       at JsonApiSerializer.Util.ReaderUtil.ReadAheadToIdentifyObject(ForkableJsonReader reader)
       at JsonApiSerializer.JsonConverters.IncludedConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
       at JsonApiSerializer.JsonConverters.DocumentRootConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
       at JsonApiSerializer.JsonConverters.DocumentRootConverter.TryResolveAsRootData(JsonReader reader, Type objectType, JsonSerializer serializer, Object& obj)
       at JsonApiSerializer.JsonConverters.ResourceObjectListConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
       at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
       at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
       at TestBed.Program.Main(String[] args) in C:\_\Thanos\TestBed\Program.cs:line 30
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

It would be useful to get the property of the object that causes this exception instead of getting an unspecified "Expected to find json object at" message. 
By The way when I use the JsonConvert.DeserializeObject<Compound[]>(t); with defaults it seems to work. Might this be an issue with the already mentioned null handling?

**Comment by alex-davies** [comment]
Can you provide an example json that is failing to deserialise, or possibly the object that you are serialising initially?

The error is giving you the json path of the property that failed, unfortunately it failed at the root which is has a path of "" which is why it looks like the message is missing data. Ill wrap quotes around the path in the exception message so its clearer when the path is an empty string.
