### ISSUE TITLE
Unable to cast object of type 'System.Int32' to type 'System.String'

### ISSUE THREAD

**Issue by wdmeest** [codecutout/JsonApiSerializer#87]
Always get following error after upgrade from 1.4.0 to >=1.5.0

```
System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.
   at JsonApiSerializer.JsonConverters.ResourceObjectConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at JsonApiSerializer.JsonConverters.DocumentRootConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 652
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriterjsonWriter, Object value, Type objectType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 80
```

**Controller method that is called and producing above error:**

    public async Task<string> GetSampleSheet(string runName)
        {
            SomeObject someObject= new SomeObject();

            var json = await Task.Factory.StartNew(() => JsonConvert.SerializeObject(someObject, Formatting.Indented, new JsonApiSerializerSettings()));
            return json;
        }

If i remove the **new JsonApiSerializerSettings()** than it works but i need the data object to appear in response.

**.csproj (.net core 2.2.0)**

    <PackageReference Include="Microsoft.AspNetCore.App" />
    ...
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" />
    <PackageReference Include="JsonApiSerializer" Version="1.6.1" />
    ...

I checked the code on line 652 of JsonSerializerInternalWriter.cs but it is not clear to me why it would fail there.

Can you help me figure out where the problem lies in?

**Comment by jonnii** [comment]
This happens because your `id` is not a `string`...

**Comment by alex-davies** [comment]
We are now accept ids as numbers or strings
